services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./client/.env
    networks:
      - public
      - internal

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server/instance:/app/instance
      - image_cache:/app/cache
    env_file:
      - ./server/.env
    networks:
      - public
      - internal

  rembg:
    build:
      context: ./server/rembg
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal

  selenium-chrome:
    image: selenium/standalone-chrome:131.0
    shm_size: "2gb"
    restart: always
    networks:
      - internal

volumes:
  uploads:
  image_cache:
    driver: local

networks:
  public:
  internal:
    internal: true
