services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./client/.env

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/instance:/app/instance
    env_file:
      - ./server/.env

  rembg:
    build:
      context: ./server/rembg
      dockerfile: Dockerfile
    restart: always

volumes:
  uploads:
